[package]
name = "camelion-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
proc-macro2 = "*"
quote = "*"
syn = { version = "*", features = ["extra-traits", "full"] }
