[package]
name = "camelion-gradient"
version = "0.1.0"
edition = "2021"

[features]
default = []
f64 = ["camelion/f64"]

[dependencies]
camelion = { path = "../../crates/camelion" }
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"
